/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import models.*;
import controller.*;

/**
 *
 * @author razee
 */
public class AddBed extends javax.swing.JFrame {

    /**
     * Creates new form AddBed
     */
    public AddBed() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // creating labels
        
        jLabel1 = new javax.swing.JLabel();
        BedSize = new javax.swing.ButtonGroup();
        BedType = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wardField = new javax.swing.JTextField();
        singleRadio = new javax.swing.JRadioButton();
        MultipleRadio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ManualRadio = new javax.swing.JRadioButton();
        SemiRadio = new javax.swing.JRadioButton();
        ElectricButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        WardCombo = new javax.swing.JComboBox<>();
        AddBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bedTable = new javax.swing.JTable();
        viewBed = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Left panel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(990, 772));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Home");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Contact us");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("About us");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 51)));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("My Profile");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 51)));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 0));
        jButton5.setText("Log Out");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 102)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iccon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3)
                .addGap(92, 92, 92)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 260, 710));

        jLabel4.setFont(new java.awt.Font("Stencil", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Add Bed ");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 230, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Ward number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        wardField.setBackground(new java.awt.Color(0, 0, 0));
        wardField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wardField.setForeground(new java.awt.Color(255, 255, 255));
        wardField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        wardField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(wardField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 170, 30));

        BedSize.add(singleRadio);
        singleRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        singleRadio.setText("Single");
        jPanel2.add(singleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, -1));

        BedSize.add(MultipleRadio);
        MultipleRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MultipleRadio.setText("Multiple");
        jPanel2.add(MultipleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Bed Size");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Bed Type");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, 40));

        BedType.add(ManualRadio);
        ManualRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManualRadio.setText("Manual");
        jPanel2.add(ManualRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        BedType.add(SemiRadio);
        SemiRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SemiRadio.setText("Semi Electric");
        jPanel2.add(SemiRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        BedType.add(ElectricButton);
        ElectricButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ElectricButton.setText("Electric");
        jPanel2.add(ElectricButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Ward Type");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 130, -1));

        WardCombo.setBackground(new java.awt.Color(0, 0, 0));
        WardCombo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        WardCombo.setForeground(new java.awt.Color(204, 0, 0));
        WardCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Emergency", "Semi Special", "ICU", "CCU", "SICU", "Special", "Deluxe", "Super Deluxe", "BurnWard", "NICU", "PICU" }));
        jPanel2.add(WardCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 120, 30));

        AddBtn.setBackground(new java.awt.Color(0, 255, 255));
        AddBtn.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(153, 0, 51));
        AddBtn.setText("Add Bed");
        AddBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)), javax.swing.BorderFactory.createCompoundBorder()), null));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel2.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 160, 50));

        bedTable.setBackground(new java.awt.Color(102, 102, 102));
        bedTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(255, 0, 51)));
        bedTable.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        bedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bed no.", "Ward no", "Bed Size", "Bed Type", "Ward Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bedTable.setRowHeight(30);
        jScrollPane1.setViewportView(bedTable);
        if (bedTable.getColumnModel().getColumnCount() > 0) {
            bedTable.getColumnModel().getColumn(0).setPreferredWidth(12);
            bedTable.getColumnModel().getColumn(1).setPreferredWidth(12);
            bedTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 480, 440));

        viewBed.setBackground(new java.awt.Color(0, 255, 255));
        viewBed.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        viewBed.setText("View Bed");
        viewBed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        viewBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBedActionPerformed(evt);
            }
        });
        jPanel2.add(viewBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 200, 50));

        jButton8.setBackground(new java.awt.Color(0, 255, 255));
        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 0, 102));
        jButton8.setText("Delete Bed");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/AddBed.png"))); // NOI18N
        jLabel2.setLabelFor(jLabel2);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 690));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 170, 30));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:

        int ward_no = Integer.parseInt(wardField.getText());
        String size = null;;
        if(singleRadio.isSelected()){
            size = "single";
        }else if(MultipleRadio.isSelected()){
            size = "multiple";
        }

        String type = null;
        if(ManualRadio.isSelected()){
            type = "manual";
        }else if(SemiRadio.isSelected()){
            type="semi-electric";

        }else if(ElectricButton.isSelected()){
            type="electric";
        }
        String wardType = null;
        Object selectedItem = WardCombo.getSelectedItem();
        if (selectedItem != null) {
            wardType = selectedItem.toString();
            
        }




        try {

            Bed b1 = new Bed(0, ward_no, type, size, wardType);
            // Bed b1 = new Bed(0, Integer.parseInt(wardField.getText()), , "42 inch", "General");
            BedController bc= new BedController();
            int result = bc.insertdetails(b1);
            if(result>0){
                JOptionPane.showMessageDialog(null, "Bed Added Successfully");
                tableadd();
            }
            else{
                JOptionPane.showMessageDialog(null, "Bed can't be added");
                
            }
            
        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(null, "e");
        
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void viewBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBedActionPerformed
        // TODO add your handling code here:
        view();
        
       
        
        
    }//GEN-LAST:event_viewBedActionPerformed


    public void table(){
        try {
            Bed d1 = new Bed(0,0,null,null,null);
            BedController sc = new BedController();
            ResultSet result = sc.selectdetails(d1);
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                int ward_no = Integer.parseInt(result.getString(4));
                String bedtype = result.getString(2);
                String bedsize = result.getString(3);
                String wardtype = result.getString(5);
                Object[] row = { id,ward_no,bedsize,bedtype,wardtype };
                DefaultTableModel model = (DefaultTableModel) bedTable.getModel();
                model.addRow(row);
            }

        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void tableadd(){
        try {
            
            Bed d1 = new Bed(0,0,null,null,null);
            BedController sc = new BedController();
            ResultSet result = sc.selectdetails(d1);
            DefaultTableModel model = (DefaultTableModel) bedTable.getModel();
            model.setRowCount(0);
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                int ward_no = Integer.parseInt(result.getString(4));
                String bedtype = result.getString(2);
                String bedsize = result.getString(3);
                String wardtype = result.getString(5);
                Object[] row = { id,ward_no,bedsize,bedtype,wardtype };
                model.addRow(row);
                
            }
        } catch (Exception e) {
            // TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void view(){
        int i = bedTable.getSelectedRow();
        if(i>0){

            TableModel model = bedTable.getModel();
            int id = Integer.parseInt(model.getValueAt(i, 0).toString());
            try {
                Bed b1 = new Bed(id, 0, null, null, null);
    
                BedController bc = new BedController();
                int out = bc.updatestatus(b1);
                int result = bc.changestatus(b1);
                dispose();
                viewBed v1 = new viewBed();
                v1.setVisible(true);
    
            } catch (Exception e) {
                // TODO: handle exception
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No row selected");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.ButtonGroup BedSize;
    private javax.swing.ButtonGroup BedType;
    private javax.swing.JRadioButton ElectricButton;
    private javax.swing.JRadioButton ManualRadio;
    private javax.swing.JRadioButton MultipleRadio;
    private javax.swing.JRadioButton SemiRadio;
    private javax.swing.JComboBox<String> WardCombo;
    private javax.swing.JTable bedTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton singleRadio;
    private javax.swing.JButton viewBed;
    private javax.swing.JTextField wardField;
    // End of variables declaration//GEN-END:variables
}
